# @package hydra.launcher

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 7200
cpus_per_task: 16
gpus_per_node: ${trainer.devices}
tasks_per_node: 1
mem_gb: 120
nodes: 1
name: ${hydra.job.name}
partition: gpu
comment: null
constraint: null
exclude: null
signal_delay_s: 120
max_num_timeout: 0
array_parallelism: 16
additional_parameters: { "mail-user": "nvaessen", "mail-type": "BEGIN,END,FAIL" }
setup:
  - source export_env.sh
  - SLEEP_TIME=${SLURM_ARRAY_TASK_ID:--1}
  - SLEEP_TIME=$(($SLEEP_TIME + 1))
  - SLEEP_TIME=$(($SLEEP_TIME * 3))
  - echo "sleeping for $SLEEP_TIME seconds"
  - sleep $SLEEP_TIME