# @package hydra.launcher

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j

partition: gpu
exclude: null

timeout_min: 7200
array_parallelism: 16

gpus_per_node: ${trainer.devices}
cpus_per_task: 16
mem_gb: 120

tasks_per_node: 1
nodes: 1
name: ${hydra.job.name}
comment: null
constraint: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters: { export: "all" }
setup:
  - ./slurm_setup.sh