_target_: src.network.wav2vec2.w2v2_speaker.Wav2vec2ForSpeakerRecognitionConfig

# settings for wav2vec2 architecture
huggingface_id: "facebook/wav2vec2-base"
reset_weights: false

# freeze logic
freeze_cnn: true
freeze_transformer: true  # this also freezes projector and rel. pos. emb
num_steps_freeze_cnn: -1 # so always
num_steps_freeze_transformer: 3_000

# if enabled, gradient checkpointing slows down iteration speed but saves memory
use_gradient_checkpointing: true

# head on top of wav2vec2 for speaker recognition
head_cfg:
  _target_: src.network.heads.LinearProjectionHeadConfig

  # settings related to architecture
  use_projection_layer: false

  # pooling method
  pool_method: mean

  # settings related to loss-function
  use_cosine_linear: true  # set to true when using aam-softmax loss

  # amount of frames in embedding sequence to use while in train mode and pooling method is "mean_chunked.
  mean_random_chunk_size: null  # ~25 ms per frame.

  # settings related to projection layer, if enabled
  projection_layer_dim: null
  projection_layer_dim_drop_prob: null

# regularisation settings
apply_spec_augment: false

mask_time_prob: 0
mask_time_length: 10
mask_time_min_masks: 2
mask_feature_prob: 0
mask_feature_length: 10
mask_feature_min_masks: 0

hidden_dropout: 0
attention_dropout: 0
feat_proj_dropout: 0
