_target_: src.networks.wav2vec2.w2v2_speaker.Wav2vec2ForSpeakerRecognitionConfig

# settings for wav2vec2 architecture
huggingface_id: "facebook/wav2vec2-base"
reset_weights: false

# freeze logic
freeze_cnn: true
freeze_transformer: true  # this also freezes projector and rel. pos. emb
num_steps_freeze_cnn: -1 # so always
num_steps_freeze_transformer: 10_000

# if enabled, gradient checkpointing slows down iteration speed but saves memory
use_gradient_checkpointing: true

# head on top of wav2vec2 for speaker recognition
head_cfg:
  _target_: src.networks.heads.LinearProjectionHeadConfig
  use_projection_layer: false
  projection_layer_dim: 128
  drop_prob: 0.05
  use_cosine_linear: false

  enable_train_chunk: false
  train_random_chunk_size: 40 # ~25 ms per frame. 40==1 second chunk size

