#_target_: src.networks.wavlm.wavlm_speech.WavLMForSpeechRecognitionConfig
_target_: src.networks.wavlm.wavlm_speech.WavLMForSpeechRecognitionConfig


# settings for wav2vec2 architecture
huggingface_id: "microsoft/wavlm-base-plus"
reset_weights: false

# freeze logic
freeze_cnn: true
freeze_transformer: true  # this also freezes projector and rel. pos. emb
num_steps_freeze_cnn: -1 # so always
num_steps_freeze_transformer: 10_000

# if enabled, gradient checkpointing slows down iteration speed but saves memory
use_gradient_checkpointing: true

# head on top of wav2vec2 for speaker recognition
head_cfg:
  _target_: src.networks.heads.LinearHeadConfig

